### ISSUE TITLE
UnpicklingError: invalid load key, '<'.

### ISSUE THREAD

**Issue by rkuo2000** [nowsyn/SIM#7]
hi,
Here's my [kaggle](https://kaggle.com/rkuo2000/semantic-image-matting)
After I correct my sim.toml, I ran into the following error message:
`!python main.py -c config/sim.toml`

2021-11-23 00:23:44,177-main.py:33-INFO-=> creating classifier 'resnet50'
2021-11-23 00:23:44,634-main.py:36-INFO-=> loading checkpoint 'checkpoints/classifier_resnet50_best.pth.tar'
2021-11-23 00:23:44,743-main.py:40-INFO-=> loaded checkpoint 'checkpoints/classifier_resnet50_best.pth.tar'
modifying input layer to accept 11 channels
2021-11-23 00:23:45,403-main.py:63-INFO-Pretrain: no checkpoint found at 'None'
2021-11-23 00:23:45,404-main.py:66-INFO-Resume: loading 'checkpoints/SIM/ckpt_best.pth'
Traceback (most recent call last):
  File "main.py", line 337, in <module>
    main()
  File "main.py", line 327, in main
    model = build_sim_model(cfg.model, logger)
  File "main.py", line 67, in build_sim_model
    ckpt = torch.load(args.resume_checkpoint, map_location=torch.device('cpu'))
  File "/opt/conda/lib/python3.7/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/opt/conda/lib/python3.7/site-packages/torch/serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.

any help ?

**Comment by nowsyn** [comment]
It seems that the model is not downloaded correctly. You may download the model again and retry the code.
